name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Angular application
        run: pnpm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm install -g angular-cli-ghpages
          npx angular-cli-ghpages --dir=dist/menu-side-bar
